version: '3.7'
# try messing with stdin_open and tty to find out correct setting
services:
  frontend:
    image: docker.ub.gu.se/ember-dev:3.14.0
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - FJARRKONTROLLEN_SERVICE_PORT=${FJARRKONTROLLEN_SERVICE_PORT}
      - FJARRKONTROLLEN_FORMS_SERVICE_PORT=${FJARRKONTROLLEN_FORMS_SERVICE_PORT}
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as debugging, etc
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container
    tty: true
    ports:
      # server
      - 4200:4200
      # livereload
      - 7020:7020
      # Tests in browser
      - 7357:7357
