cas_url: <%= ENV["FORMS_CAS_URL"] ? ENV["FORMS_CAS_URL"] : 'https://idp3.it.gu.se/idp/profile/cas' %>
fjarrkontrollen:
  base_url: <%= ENV["FJARRKONTROLLEN_SERVER_URL"] %>
  access_token: <%= ENV["FJARRKONTROLLEN_SERVER_ACCESS_TOKEN"] %>
koha:
  base_url: <%= ENV["FORMS_KOHA_SVC_URL"] %>
  user: <%= ENV["FORMS_KOHA_USER"] %>
  password: <%= ENV["FORMS_KOHA_PASSWORD"] %>
oauth2:
  client_id: <%= ENV["GUB_OAUTH2_CLIENT_ID"] %>
  client_secret: <%= ENV["GUB_OAUTH2_CLIENT_SECRET"] %>
