cas_url: https://idp3.it.gu.se/idp/profile/cas
fjarrkontrollen:
  base_url: <%= ENV["FJARRKONTROLLEN_SERVER_URL"] %>
  access_token: <%= ENV["FJARRKONTROLLEN_SERVER_ACCESS_TOKEN"] %>
koha:
  base_url: <%= ENV["KOHA_SVC_URL"] %>
  user: <%= ENV["KOHA_USER"] %>
  password: <%= ENV["KOHA_PASS"] %>
